name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          cd angular-app
          npm install

      - name: Run Build
        run: |
          cd angular-app
          npm run build

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./angular-app/public

  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    # only run if build job complte successfully
    needs: [build]
    steps:
      # building the app before deploy
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "20.x"
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: |
          cd angular-app
          npm install
      # build the app
      - name: Build the app artifact for prod
        run: |
          cd angular-app
          npm run build --prod

      - name: Navigate to Angular App directory
        run: cd angular-app && ls
        
      - name: Check for firebase.json
        run: |
          if [ ! -f "firebase.json" ]; then
            echo "firebase.json not found in the Angular App directory."
            exit 1
          fi

      # ddeploy the app artifact to firebase
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
