name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          cd angular-app
          npm ci

      - name: Run Build
        run: |
          cd angular-app
          npm run build

      - name: Archive Production Artifacts
        uses: actions/upload-artifacts@master
        with:
          name: public
          path: ./angular-app/public

  deploy:
    name: Firebase Deployment
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Get Latest Build Artifact
        uses: actions/download-artifacts@v2
        with:
          name: public
          path: ./angular-app/public

      - name: Deploy Angular App to Firebase
        run: |
          cd angular-app
          npx firebase deploy --only hosting --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
