name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          cd angular-app
          npm install

      - name: Run Build
        run: |
          cd angular-app
          npm run build

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./angular-app/public

  deploy:
    name: Firebase Deployment
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Get Latest Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./angular-app/public

      - name: Navigate to angular-app directory
        run: cd angular-app

      - name: Deploy Angular App to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_token }}
