name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public

  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    # only run if build job complte successfully
    needs: [build]
    steps:
      # Get Artifact from latest build
      - name: Get Latest Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Login to Firebase
        run: firebase login:ci --interactive --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy angular app to Firebase
        run: firebase deploy --only hosting
